version: "3.8"

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - NODE_ENV=production

  # backend:
  #   container_name: backend
  #   build: ./api
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=production

  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
